version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: clothing-search-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend

#  app:
#    build: .
#    container_name: clothing-search-api
#    ports:
#      - "8000:8000"
#    depends_on:
#      - postgres
#    environment:
#      - POSTGRES_SERVER=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=app
#      - POSTGRES_PORT=5432
#      - SECRET_KEY=${SECRET_KEY:-your-secret-key-for-jwt-here-use-openssl-rand-base64-32}
#    restart: always
#    networks:
#      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge